name: Schedule

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 2 hours

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deployment
        env:
          REDEPLOY: ${{ secrets.REDEPLOY }}
        run: |
          curl -X POST "$REDEPLOY"
