name: Schedule

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 2 hours



  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel deployment
        run: |
          curl -X POST "$REDEPLOY"
