# name: Schedule API call

# on:
#   schedule:
#     - cron: '*/15 * * * *' # Runs every day at midnight UTC

# jobs:
#   call-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Call API route
#         run: |
#           curl https://astrodaisy.vercel.app/api/tweetTest